### ISSUE TITLE
Price tracker background

### ISSUE THREAD

**Issue by esemi** [esemi/wb-price-tracker#6]
DOD
---
- [ ] fetch all subscribed SKU
- [ ] fetch price from WB
- [ ] save price and diff
- [ ] create notify for subscribers (only if price changed)
